# Generated by Django 2.0 on 2022-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emee_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='号码')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已使用'), (2, '未使用')], verbose_name='状态')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='depart',
            field=models.CharField(max_length=32, verbose_name='部门名称'),
        ),
    ]
