# Generated by Django 2.0 on 2022-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emee_manage', '0002_auto_20220914_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='昵称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
