# Generated by Django 2.0 on 2022-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emee_manage', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.CharField(default='测试', max_length=32, verbose_name='测试'),
        ),
    ]
