# Generated by Django 2.0 on 2022-10-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emee_manage', '0006_order_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='test',
        ),
    ]
