# Generated by Django 2.0 on 2022-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emee_manage', '0007_remove_order_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=32, verbose_name='年龄')),
                ('img', models.CharField(max_length=128, verbose_name='头像路径')),
            ],
        ),
    ]
